### ISSUE TITLE
Should I make savefilesetup become singleton class?

### ISSUE THREAD

**Issue by trinhquyswe** [StylishEsper/ESave#1]

**Comment by EsperGames** [comment]
You are free to do whatever is best for your project. Please note that the SaveFileSetup class is a component. If you make it static, it can't be used as such.

**Comment by trinhquyswe** [comment]
I have 2 savefilesetup components in 2 different gameobjects, I set the file name and file path the same, but the component in this gameobject cannot get the file from the other component, I don't know if it is a bug or because of it but so, so I just want to create a single instance of savefilesetup

**Comment by EsperGames** [comment]
If the name and path are the same, then they should be targeting the same file in the user's system.

Are you getting a certain error?

**Comment by trinhquyswe** [comment]
sorry, the error was caused because I did not carefully test one of the components
